In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from pandas import DataFrame

import matplotlib as mpl
mpl.use('Agg')

import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
# 終値情報を持つcsvから価格を得ます
def importData():
    btc_price = pd.read_csv('/Users/ryokikuchi/Documents/work/tech/python/Lesson/Lesson1/Chapter16/coindesk-bpi-USD-close_data-2010-07-18_2018-02-25.csv')
    data = np.array(btc_price)
    return data

In [21]:
data = np.array(importData())

# ここでは15時間前までを見るものとします
hour_ago = 15

X = np.zeros((len(data), hour_ago))
X

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [24]:
# 時間による推移を見て、そこから偏差を学習できるようにします
for i in range(0, hour_ago):
    X[i:len(data), i] = data[0:len(data) - i, 1]

Y = np.zeros(len(data))
Y

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [25]:
# 予測する時間を指定します
predict_time = 1

Y[0:len(Y)-predict_time] = X[predict_time:len(X), 0] - X[0:len(X)-predict_time, 0]
Y

array([ -1.00000000e-02,  -1.00000000e-02,   1.00000000e-02, ...,
        -4.67080000e+02,   7.97700000e+01,   0.00000000e+00])

In [30]:
X

array([[  9.00000000e-02,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  8.00000000e-02,   9.00000000e-02,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  7.00000000e-02,   8.00000000e-02,   9.00000000e-02, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       ..., 
       [  1.01494600e+04,   9.83043000e+03,   1.04561700e+04, ...,
          8.07080000e+03,   8.55661000e+03,   8.68984000e+03],
       [  9.68238000e+03,   1.01494600e+04,   9.83043000e+03, ...,
          8.89121000e+03,   8.07080000e+03,   8.55661000e+03],
       [  9.76215000e+03,   9.68238000e+03,   1.01494600e+04, ...,
          8.51624000e+03,   8.89121000e+03,   8.07080000e+03]])

In [19]:
#学習では、50~1800行目を使うものとします。これは情報の偏りを防ぐためのものであり、全体でも構いません
train_x = X[50:1800, :]
train_y = Y[50:1800]
train_y

array([ 0.  ,  0.  ,  0.  , ...,  1.71, -1.25,  2.76])

In [32]:
# 残りの全てをテストデータとします
test_x = X[1800:len(X)-predict_time, :]
test_y = Y[1800:len(Y)-predict_time]

#TODO: LinearRegression を使用して線形回帰モデルで学習させよう
model = linear_model.LinearRegression()
model.fit(train_x, train_y)

#TODO: pred_y に対して、学習結果を代入しましょう
pred_y = model.predict(test_x)

# 予測結果を出力します
result = pd.DataFrame(pred_y)
result.columns = ['pred_y']
result['test_y'] = test_y

# 結果を output.png に保存します
sns.set_style('whitegrid')
sns.regplot(x='pred_y', y='test_y', data=result)
plt.title('Bitcoin Price')
plt.savefig('output.png')

array([['2010-07-18 00:00:00', 0.09],
       ['2010-07-19 00:00:00', 0.08],
       ['2010-07-20 00:00:00', 0.07],
       ..., 
       ['2018-02-23 00:00:00', 10149.46],
       ['2018-02-24 00:00:00', 9682.38],
       ['2018-02-25 02:07:00', 9762.15]], dtype=object)